name: Examples E2E (old nodes)
on: [push]
jobs:
  e2e-old-nodes:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        dir: [.interop/next-prisma-starter]
        # start example with:
        node-start: ['14.x']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-

      - run: node -v
      - name: Install deps and build (with cache)
        run: pnpm --filter ./examples/${{ matrix.dir }}  --filter "@trpc/*" --filter root install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/examples/${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-start }}

      - run: node -v

      - name: if exists, run build-sqlite, else run build
        run: |
          cat ./examples/${{ matrix.dir }}/package.json | 
          if grep --silent '"build-sqlite"'; 
            then pnpm --filter ./examples/${{ matrix.dir }} build-sqlite; 
            else pnpm --filter ./examples/${{ matrix.dir }} build;
          fi

      - name: if exists, run test-start
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-start
      - name: if exists, run test-dev
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-dev
