name: Examples E2E
on: [push]
jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        dir:
          [
            express-server,
            next-chat,
            next-prisma-starter,
            next-prisma-todomvc,
            standalone-server,
          ]
        node: ['14.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - run: yarn --cwd examples/${{ matrix.dir }} build
        env:
          DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
      - run: yarn --cwd examples/${{ matrix.dir }} test-start
        env:
          DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
      - run: yarn --cwd examples/${{ matrix.dir }} test-dev
        env:
          DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
