name: Examples E2E
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    container:
      image: mcr.microsoft.com/playwright:v1.20.0-focal
      options: --user 1001
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright
      DATABASE_URL: postgresql://postgres:@postgres:5432/trpcdb
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      matrix:
        dir: [
            .interop/express-server,
            .interop/next-prisma-starter,
            .interop/next-prisma-starter-websockets,
            .interop/next-prisma-todomvc,
            .interop/standalone-server,
            .interop/fastify-server,
            .interop/cloudflare-workers,
            next-prisma-starter,
            # next-prisma-starter-websockets,
            # next-prisma-todomvc,
            standalone-server,
          ]
        node-start: ['16.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: node -v
      - uses: bahmutov/npm-install@v1

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-start }}

      - run: node -v

      - name: if exists, run yarn lint
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"lint"'; then yarn lint; fi
      - name: if exists, run yarn build
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"build"'; then yarn build; fi
      - name: if exists, run yarn test-start
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"test-start"'; then yarn test-start; fi
      - name: if exists, run yarn test-dev
        run: cd examples/${{ matrix.dir }} && cat package.json | if grep --silent '"test-dev"'; then yarn test-dev; fi
