name: Build & Test
on: [push]
jobs:
  test:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright

    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache Playwright's binary
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-playwright-bin-v1.26.0
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Install deps and build (with cache)
        run: pnpm install --child-concurrency 3

      - name: Test
        run: pnpm test -- --ci --coverage --maxWorkers=2

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./packages
